# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'project.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FirstWindow(object):
    def setupUi(self, FirstWindow):
        FirstWindow.setObjectName("FirstWindow")
        FirstWindow.setFixedSize(600, 400)
        self.centralwidget1 = QtWidgets.QWidget(FirstWindow)
        self.centralwidget1.setObjectName("centralwidget1")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget1)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(-1, -1, 601, 71))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_1_1 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_1_1.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_1_1.setObjectName("verticalLayout_1_1")
        self.label_1_1 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_1_1.setObjectName("label_1_1")
        self.verticalLayout_1_1.addWidget(self.label_1_1)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget1)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(30, 60, 581, 241))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2_1 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2_1.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2_1.setObjectName("verticalLayout_2_1")
        self.label_2_1 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_2_1.setText("")
        self.label_2_1.setPixmap(QtGui.QPixmap("Фон.png"))
        self.label_2_1.setObjectName("label_2_1")
        self.verticalLayout_2_1.addWidget(self.label_2_1)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget1)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 330, 581, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout1 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout1.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout1.setObjectName("horizontalLayout1")
        self.lineEdit1 = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit1.setObjectName("lineEdit1")
        self.horizontalLayout1.addWidget(self.lineEdit1)
        self.search1 = QtWidgets.QToolButton(self.horizontalLayoutWidget)
        self.search1.setObjectName("search1")
        self.horizontalLayout1.addWidget(self.search1)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget1)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 310, 581, 21))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3_1 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3_1.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3_1.setObjectName("verticalLayout_3_1")
        self.label_3_1 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_3_1.setObjectName("label_3_1")
        self.verticalLayout_3_1.addWidget(self.label_3_1)
        self.cancell1 = QtWidgets.QPushButton(self.centralwidget1)
        self.cancell1.setGeometry(QtCore.QRect(515, 370, 75, 23))
        self.cancell1.setObjectName("cancell1")
        self.next1 = QtWidgets.QPushButton(self.centralwidget1)
        self.next1.setGeometry(QtCore.QRect(435, 370, 75, 23))
        self.next1.setObjectName("next1")
        FirstWindow.setCentralWidget(self.centralwidget1)

        self.retranslateUi(FirstWindow)
        QtCore.QMetaObject.connectSlotsByName(FirstWindow)

    def retranslateUi(self, FirstWindow):
        _translate = QtCore.QCoreApplication.translate
        FirstWindow.setWindowTitle(_translate("FirstWindow", "Background Remover"))
        FirstWindow.setWindowIcon(QtGui.QIcon('icon.png'))
        self.label_1_1.setText(_translate("FirstWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt; font-weight:600;\">Background remover</span></p></body></html>"))
        self.search1.setText(_translate("FirstWindow", "..."))
        self.label_3_1.setText(_translate("FirstWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Вкажіть шлях до файлу, у якому хочете видалити задній фон:</span></p></body></html>"))
        self.cancell1.setText(_translate("FirstWindow", "Скасувати"))
        self.next1.setText(_translate("FirstWindow", "Далі"))



