# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'project2.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SecondWindow(object):
    def setupUi(self, SecondWindow):
        SecondWindow.setObjectName("SecondWindow")
        SecondWindow.setFixedSize(600, 400)
        self.centralwidget2 = QtWidgets.QWidget(SecondWindow)
        self.centralwidget2.setObjectName("centralwidget2")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget2)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 330, 581, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout2.setObjectName("horizontalLayout2")
        self.lineEdit2 = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit2.setObjectName("lineEdit2")
        self.horizontalLayout2.addWidget(self.lineEdit2)
        self.search2 = QtWidgets.QToolButton(self.horizontalLayoutWidget)
        self.search2.setObjectName("search2")
        self.horizontalLayout2.addWidget(self.search2)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget2)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 601, 71))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_1_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_1_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_1_2.setObjectName("verticalLayout_1_2")
        self.label_1_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_1_2.setObjectName("label_1_2")
        self.verticalLayout_1_2.addWidget(self.label_1_2)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget2)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(30, 60, 581, 241))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2_2.setObjectName("verticalLayout_2_2")
        self.label_2_2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_2_2.setText("")
        self.label_2_2.setPixmap(QtGui.QPixmap("Фон.png"))
        self.label_2_2.setObjectName("label_2_2")
        self.verticalLayout_2_2.addWidget(self.label_2_2)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget2)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 310, 581, 21))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3_2.setObjectName("verticalLayout_3_2")
        self.label_3_2 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_3_2.setObjectName("label_3_2")
        self.verticalLayout_3_2.addWidget(self.label_3_2)
        self.cancell2 = QtWidgets.QPushButton(self.centralwidget2)
        self.cancell2.setGeometry(QtCore.QRect(515, 370, 75, 23))
        self.cancell2.setObjectName("cancell2")
        self.go = QtWidgets.QPushButton(self.centralwidget2)
        self.go.setGeometry(QtCore.QRect(435, 370, 75, 23))
        self.go.setObjectName("go")
        self.back1 = QtWidgets.QPushButton(self.centralwidget2)
        self.back1.setGeometry(QtCore.QRect(355, 370, 75, 23))
        self.back1.setObjectName("back1")
        SecondWindow.setCentralWidget(self.centralwidget2)

        self.retranslateUi(SecondWindow)
        QtCore.QMetaObject.connectSlotsByName(SecondWindow)

    def retranslateUi(self, SecondWindow):
        _translate = QtCore.QCoreApplication.translate
        SecondWindow.setWindowTitle(_translate("SecondWindow", "Background Remover"))
        SecondWindow.setWindowIcon(QtGui.QIcon('icon.png'))
        self.search2.setText(_translate("SecondWindow", "..."))
        self.label_1_2.setText(_translate("SecondWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt; font-weight:600;\">Background remover</span></p></body></html>"))
        self.label_3_2.setText(_translate("SecondWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Вкажіть папку, у якій хочете зберегти оброблене зображення:</span></p></body></html>"))
        self.cancell2.setText(_translate("SecondWindow", "Скасувати"))
        self.go.setText(_translate("SecondWindow", "Обробити"))
        self.back1.setText(_translate("SecondWindow", "Назад"))




